### ISSUE TITLE
Twitter points problem

### ISSUE THREAD

**Issue by hassanalizadeh** [workchainio/bug-bounty#106]
I can't get Twitter Retweet, Twitter Like and Share your workID points in bounty page after days trying to get them. I did all things on it's help page (
https://help.workchain.io/workchain-io-bounty-and-airdrop/bounty-points-guide/points-twitte), but it did not work for me. Even I can't fine anything about "Share your workID" and "Period Limit: 200PTS". What I have to do to get these points?

You should describe all parts of points in details, and it should work some easy way! 

**Screenshot**
<img width="278" alt="screen shot 1397-05-16 at 10 46 30 am" src="https://user-images.githubusercontent.com/13905132/43758438-5627a734-9a31-11e8-8335-2ca49d8e39a2.png">

MacBook 2016:
 - OS: Mac OS 10.13.6 (17G65)
 - Browser: Safari 11.1.2 (13605.3.8)

**Comment by ryanpaulfyfe** [comment]
Thanks for reporting, our tam is working to resolve this.
