### ISSUE TITLE
Click link on Bitcointalk Forum Verficiation (i.e.  Got to Thread) redirects to the the page of Bitcoin tal. But unable to post message . This is Bug

### ISSUE THREAD

**Issue by paragsanyasi** [workchainio/bug-bounty#115]
**Describe the bug**

**To Reproduce**
1. Go to 'Bitcointalk Forum Verficiation'
2. Click on 'Got to Thread'
3. Scroll down to 'Unable to post the message' after page appeared.

**Expected behavior**
Post tesxt box should be visible easily and user should able to post the message
![no post textbox 1](https://user-images.githubusercontent.com/26295023/43774439-b7b89294-9a66-11e8-8f35-514f26021c27.jpg)
![no post textbox 2](https://user-images.githubusercontent.com/26295023/43774441-b7dfe8a8-9a66-11e8-99b8-d6a4325a38cd.jpg)

**Screenshots**
Attached 

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
Click link on Bitcointalk Forum Verficiation (i.e.  Got to Thread) redirects to the the page of Bitcoin tal. But unable to post message . This is Bug

**Comment by ryanpaulfyfe** [comment]
You must be logged in on the forum, and the forum software is not our own so we cannot control their UI. If you are still having issues please contact our team at: ping@workchain.io
