### ISSUE TITLE
Points from Twitter and Medium task not added uo

### ISSUE THREAD

**Issue by tiennvdtn** [workchainio/bug-bounty#116]
**Describe the bug**
I did all tasks of Medium and Twitter but just some marked as done.

**To Reproduce**
1. Go to Bounty page
2. Do all Medium and Twitter tasks

**Expected behavior**
Tasks should be marked as done and points added up

**Screenshots**
![image](https://user-images.githubusercontent.com/40050370/43776593-8a585596-9a7a-11e8-894f-92d0346bfd5d.png)

Please fix this issue quickly, I did tasks for 2 days and Facebook tasks also

**Comment by ryanpaulfyfe** [comment]
Thanks, our team is aware of this and looking into a fix as well as UI improvements to make things more clear
