### ISSUE TITLE
Socials Period Limit not be updated

### ISSUE THREAD

**Issue by tiennvdtn** [workchainio/bug-bounty#117]
**Describe the bug**
In bounty page, I see the Facebook Period limit and Twitter Period Limit in navbar/ 
But I think It's showing wrong value
I earned 400 points from Facebook and 750 from Twitter, but only 0 and 150 in the navbar.
Please see the screenshots

**To Reproduce**
1. Do all Facebook and Twitter tasks
2. Go to bounty page

**Expected behavior**
Facebook and Twitter should show the correct value

**Screenshots**
![image](https://user-images.githubusercontent.com/40050370/43777044-de70976e-9a7b-11e8-938f-427b1bd99408.png)

Please fix this issue quickly, this is frontend part, all users can see it

**Comment by ryanpaulfyfe** [comment]
Thanks, we are aware of this and our team is working to resolve
