### ISSUE TITLE
twitter account changing issue

### ISSUE THREAD

**Issue by alexjoan55** [workchainio/bug-bounty#126]
you are not able to change twitter account or can you?

**To Reproduce**

1. Go to 'https://workchain.io/bounty'
2. Go to twitter section its says "Account Linked" ignore it
3. Right click on "Account Linked"
2. Click on 'inspect element'
4. Find "g-btn bounty-card__button g-btn--disabled g-btn--success" and change to "g-btn bounty-card__button g-btn--enabled g-btn--success"
4. Close webmaster tools
5. Click "Account Linked"
6. Click "allow" for WorkChain.io app
7. your new twitter account linked

**Comment by ryanpaulfyfe** [comment]
Linked accounts cannot be changed at this time
