### ISSUE TITLE
Try to access Dashboard when logged out

### ISSUE THREAD

**Issue by Gutem** [workchainio/bug-bounty#130]
If you try to access https://workchain.io/home logged out, the application will process the request, start an API call, render a small part of Dashboard and, only after that, redirect you.

**To Reproduce**
1. Go to https://workchain.io/home
2. If logged in, log out and revisit the page

The app don't behavior like this, should verify if the user is logged in before start to render anything.
If the user is not logged in, redirect to login.

Tested on macOS Mojave Beta 5, Firefox 61.0.1 (64-bit)

**Comment by ryanpaulfyfe** [comment]
This is our current expected behaviour, but noted for improvement, thanks for reporting.
