### ISSUE TITLE
I have not got the twitter points

### ISSUE THREAD

**Issue by Sunil4sha** [workchainio/bug-bounty#134]
Hi,

Team
![telegarm points](https://user-images.githubusercontent.com/32510870/43813882-530a831e-9ae5-11e8-8820-fa3fa9952b6b.png)

I have not got the twitter points

user name : sunil4.sha@gmail.com

Regards,
Sunil

**Comment by toruasoki** [comment]
Yes , I'm yet to get my tweeter points for liking, tweeting and retweeting.

**Comment by ryanpaulfyfe** [comment]
Please email us at ping@workchain.io with more information, including your workchain username/email as well as your twitter username and links to your tweets
