### ISSUE TITLE
[Improve] Workchain setting 

### ISSUE THREAD

**Issue by halinh12310** [workchainio/bug-bounty#135]
**Describe the bug**
In [Workchain setting ](https://workchain.io/settings) I think you should improve:
- Edit short URL for my default workID -> You should allow separating characters like "_", "-", "."
- Activity on my account -> Added option to report suspicious behavior. For example, access from addresses I do not know ...

**Screenshots**
![improve setting](https://user-images.githubusercontent.com/6305130/43814408-311c0ec4-9b05-11e8-94a0-899fad4c8357.PNG)

**Comment by ryanpaulfyfe** [comment]
Thanks for the suggested improvements!
