### ISSUE TITLE
Lacks of HTTP Strict Transport Security 

### ISSUE THREAD

**Issue by Gutem** [workchainio/bug-bounty#136]
HTTP Strict Transport Security is an excellent feature to support on your site and strengthens your implementation of TLS by getting the User Agent to enforce the use of HTTPS. 

1. If you use the Firefox's Inspector and go to "Network" tab you won't see the HSTS header at "headers" tab, on right panel.

Recommended value "strict-transport-security: max-age=31536000; includeSubDomains".

Tested on macOS Mojave Beta 5 and Firefox 61.0.1(64-bit)

**Comment by ryanpaulfyfe** [comment]
Thanks for this suggestion
