### ISSUE TITLE
[Improve]  Workchain wallet

### ISSUE THREAD

**Issue by halinh12310** [workchainio/bug-bounty#140]
**Describe the bug**
"Your WATT Ethereum Wallet" -> Does not offer "add your wallet" options?

**Screenshots**
![improve workchain wallet](https://user-images.githubusercontent.com/6305130/43815095-e5129562-9b08-11e8-8d7f-ff1bd6d37d23.PNG)

**Comment by ryanpaulfyfe** [comment]
Please see: https://help.workchain.io/the-workchain-io-app/workid-wallet/workid-wallet
