### ISSUE TITLE
 Bitcointalk can not login

### ISSUE THREAD

**Issue by Baonguyen7412** [workchainio/bug-bounty#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Baonguyen7412** [comment]
Bitcointalk can not login

**Comment by Baonguyen7412** [comment]
Bitcointalk can not login

**Comment by ryanpaulfyfe** [comment]
Bitcointalk  is a 3rd party service, not ours.
