### ISSUE TITLE
Bounty Points Verification Bug!!!!!

### ISSUE THREAD

**Issue by mukundsuthar5** [workchainio/bug-bounty#146]
**Describe the bug**
Bounty Points for Facebook,Twitter,BitcoinTalk Are not not working.

**To Reproduce**
1. Go to 'https://workchain.io/bounty'
2. Click on 'https://www.facebook.com/workchain.io'
3. Scroll down to 'Post & Complete task'

**Expected behavior**
Whenever i complete a task to any social media platform & come back to Bounty site it should automatically add to our profile which is not happen till long time.

**Screenshots**

![untitled](https://user-images.githubusercontent.com/14370807/43822768-b57d27a2-9b0a-11e8-8d65-a90d10ffce47.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome]
 - Version [68]

**Smartphone (please complete the following information):**
 - Device: [iPhone6s Plus]
 - OS: [iOS 12 beta 5]
 - Browser [safari]
 - Version [Default]

**Additional context**
Same Problem is With My BitcoinTalk Bounty,Workid Bio,Medium Clap.

**Comment by ryanpaulfyfe** [comment]
Duplicate Report. But thanks!
