### ISSUE TITLE
Bounty - Facebook bug

### ISSUE THREAD

**Issue by karthibanhbk** [workchainio/bug-bounty#149]
Your environment (Browser, Operating System, etc): Chrome browser, Windows 10 Enterprise edition
Summary of Issues: I have followed the Facebook page, Liked a post and Shared my work ID; however, the points are not updated and thus causing the bug to award points to the user (refer screenshots).
Expected behavior: Once the necessary actions are performed, the bounty program should automatically sync and update rewards. 
Screen shots: 
![pic 1](https://user-images.githubusercontent.com/36513591/43831055-87806e0c-9b20-11e8-80e9-c3eb8feb381a.JPG)
![pic 2](https://user-images.githubusercontent.com/36513591/43831064-90b6a55e-9b20-11e8-9dea-9f8c0bfa9984.JPG)
![pic 3](https://user-images.githubusercontent.com/36513591/43831071-94e4adba-9b20-11e8-8462-80be25bab309.JPG)
![pic 4](https://user-images.githubusercontent.com/36513591/43831079-98d5d64c-9b20-11e8-8a73-ce7da4b4b54c.JPG)

Thanks,
Karthiban Kumar

**Comment by ryanpaulfyfe** [comment]
Known issue, our team is working on it
