### ISSUE TITLE
Authentication Code Issues and Twitter Verification 

### ISSUE THREAD

**Issue by Ak2young** [workchainio/bug-bounty#159]
I registered some mins ago.... Having clicked on my email activation link.... It surely took me to my homepage....
Mistakenly closed the page and what I tried logging  in again.... API AUTHENTICATION CODE it is....
What the HELL !!! 
Where do I get that from without a formal authentication code...
This kept me locked out for a while 
I decided to use my Twitter to log in and see if it's gonna work.... 
Lo and behold... It took me in.... 
On getting to linking my Twitter Account.... 
Your site kept bouncing me.... Saying my Twitter account t has already been used.... Who used it, if I may ask..... 

Now am Scared to log out as I might not be able to get in back... And my Twitter account is still misbehaving...

Get ALl these fixed Pls...

**Comment by ryanpaulfyfe** [comment]
Please follow our bug reporting guidelines as we cannot reproduce this and this is not following the template provided. If there are multiple issues you are having, report multiple bugs.

**Comment by Ak2young** [comment]
If you have problems with this......... Solve the bugs you understand....
