### ISSUE TITLE
Bitcointalk Profile website

### ISSUE THREAD

**Issue by moncuk** [workchainio/bug-bounty#182]
**Describe the bug**
After adding the web site on bitcointalk task dont close
**To Reproduce**
1. Go to 'www.bitcointalk.com  ' and login
2. Click on 'forum profile information'
3. Scroll down to Website URL area 
4. 'write https://workchain.io ' and click change profile
5. go to airdrop page and refresh. Still task there
![ekran resmi 2018-08-11 02 28 25](https://user-images.githubusercontent.com/41038055/44041501-9e446c42-9f26-11e8-83d1-dab142c61d01.png)

**Comment by ryanpaulfyfe** [comment]
Because of changes on bitcoin talk, they closed our thread without notice, we unfortunately can no longer continue with this campaign as we don't have a way to verify profiles anymore. We are working with them to see if we can get it re-opened for a future campaign.
