### ISSUE TITLE
Bug bounty: Facebook verification problem in Airdrop box

### ISSUE THREAD

**Issue by jkarlosb** [workchainio/bug-bounty#192]
**Describe the bug**
Verification is not working with Facebook into Airdrop box

**To Reproduce**
1. Verify your Facebook account in WorkChain dashboard
2. Enter WorkChain.io Facebook page and like page
3. Access to bounty program, Airdrop red button
4. "Verify + Like Page for Facebook" text is not strikethrough

**Expected behavior**
"Verify + Like Page for Facebook" text inside Airdrop box  is strikethrough, and it shows I am participate in Airdrop

**Screenshots**
![screen shot 2018-08-16 at 11 08 45](https://user-images.githubusercontent.com/16191657/44199562-cdf47c00-a144-11e8-9ea4-de255adcb558.png)
![screen shot 2018-08-16 at 11 08 10](https://user-images.githubusercontent.com/16191657/44199565-cfbe3f80-a144-11e8-8220-cf98d74f0c3f.png)
![screen shot 2018-08-16 at 11 07 58](https://user-images.githubusercontent.com/16191657/44199573-d3ea5d00-a144-11e8-82b9-95987a451903.png)

**Desktop (please complete the following information):**
 - Browser: Google Chrome

**Comment by ipetrovic11** [comment]
Hi jkarlosb ,

Can you please contact me via Telegram and share your email.
