### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by trottyosmy** [workchainio/bug-bounty#25]
**Describe the bug**
Are you looking for a job?
No

Can not clickable, or where is the yes answer. Strange.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trottyosmy** [comment]
![issue - bug report](https://user-images.githubusercontent.com/42069332/43666697-36b76ccc-9775-11e8-8131-32340cd337d9.jpg)

**Comment by sumcent** [comment]
Here comes a significant project
