### ISSUE TITLE
not credit point for tasking facebook

### ISSUE THREAD

**Issue by chikal1** [workchainio/bug-bounty#262]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 7 ultimate
 - Browser : chrome
 - Version : Version 68.0.3440.106 (Official Build) (64-bit)
![38](https://user-images.githubusercontent.com/39870793/45551676-e1d0f200-b858-11e8-8c5e-6321a1791a3b.png)

**Comment by oveed** [comment]
i have like and share 6 post

**Comment by Catalizer123** [comment]
good
