### ISSUE TITLE
Not getting points from Twitter and Facebook

### ISSUE THREAD

**Issue by JackSparrow190000** [workchainio/bug-bounty#60]
**Describe the bug**
I verified my Twitter and Facebook but when I retweet or like a post, it does not give me the points.
Even after waiting over 10+ hours I have not gotten my points.

**To Reproduce**
1. Go to https://twitter.com/workchain_io
2. Click on Retweet or like
3. Wait 2 hours and see that you haven't gotten your points

**Expected behavior**
When I retweet something or like a post, I should get my points as soon as possible
<img width="400" alt="1" src="https://user-images.githubusercontent.com/42108656/43683758-04a42e56-989b-11e8-845a-0896067e5979.PNG">
<img width="945" alt="2" src="https://user-images.githubusercontent.com/42108656/43683759-074261b4-989b-11e8-8892-12a98ce48706.PNG">

.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shaibuwhyte** [comment]
Am not getting point on twitter

**Comment by ryanpaulfyfe** [comment]
Thanks for the report, this is a known issue which our team is working to resolve.
