### ISSUE TITLE
Incorrect number of PTS for bitcointalk

### ISSUE THREAD

**Issue by ghost** [workchainio/bug-bounty#62]
![Bitcointalk](http://ipic.su/img/img7/fs/Snimok.1533463594.png)

![Bitcointalk](http://ipic.su/img/img7/fs/Snimok2.1533463667.png)

workID: https://workchain.io/workid/LYJGDybK8rgSGXfYVIG0EjARf6Nhqw9x7xRRqsGn

**Comment by ghost** [comment]
Incorrect number of PTS for bug bounty, it is written 2000 PTS, but have added 100 PTS, bug!

![bugs](http://ipic.su/img/img7/fs/Snimok.1533573222.png)

**Comment by ghost** [comment]
![BUGS](http://ipic.su/img/img7/fs/Snimok.1533573855.png)

**Comment by ghost** [comment]
Completed all the tasks in Facebook and Twitter, but the PTS did not accrue.

Facebook: https://www.facebook.com/dev.afonichev
Twitter: https://twitter.com/afonichev_dev

![BUGS](http://ipic.su/img/img7/fs/Snimok.1533574204.png)

**Comment by Afonichev** [comment]
What's happening?

![BUG](http://ipic.su/img/img7/fs/Snimok.1534603250.png)
