### ISSUE TITLE
Error when calculating the scores in the company Facebook.

### ISSUE THREAD

**Issue by Lina5588** [workchainio/bug-bounty#65]
My Facebook account has been verified, but no points are awarded for completing tasks. It's been more than three days. 
I work on a smartphone, android 7.0 system, Google Chrome browser.
I've been doing likes and repost on my page for a few days. But on the bounty page, the points for completing the tasks of this company are 0. This is seen in the screenshot.
![screenshot_20180805-144804](https://user-images.githubusercontent.com/39458410/43685641-6b84596a-98bf-11e8-890d-39929e25521a.png)
You can check at my Facebook profile https://www.facebook.com/Lina558874 For example, here is a link to one of several publications https://www.facebook.com/story.php?story_fbid=1654794214631767&id=100003036139763

**Comment by dulowegner** [comment]
The team is working extremely hard to verify those relative issues..... It will be over in no sooner time.
