### ISSUE TITLE
Not receiving points from Facebook

### ISSUE THREAD

**Issue by JackSparrow190000** [workchainio/bug-bounty#69]
**Describe the bug**
I liked, shared and posted my workId, but I haven't gotten any points.
**To Reproduce**
1. Go to https://www.facebook.com/workchain.io
2. Click on Like or Share

**Expected behavior**
I would like to get my points asap when I complete the tasks.
**Screenshots**

<img width="354" alt="proof 1" src="https://user-images.githubusercontent.com/42108656/43686528-673eae3a-98d0-11e8-9fdd-9d051e77d61e.PNG">
<img width="388" alt="proof 2" src="https://user-images.githubusercontent.com/42108656/43686529-68e4a14a-98d0-11e8-98d8-cb83024760fc.PNG">
<img width="193" alt="proof 3" src="https://user-images.githubusercontent.com/42108656/43686531-69dbaecc-98d0-11e8-9064-5d1f985af6c4.PNG">
<img width="946" alt="proof 4" src="https://user-images.githubusercontent.com/42108656/43686532-6ab14712-98d0-11e8-8612-920856f6cecb.PNG">

**Comment by shaibuwhyte** [comment]
Am not receiving all facebook point

**Comment by ryanpaulfyfe** [comment]
Known issue that our team is working to resolve. Thanks for reporting.
