### ISSUE TITLE
[Facebook] About confirm the account is connected

### ISSUE THREAD

**Issue by halinh12310** [workchainio/bug-bounty#81]
**Describe the bug**
If I like your fanpage before authorizing facebook app, it looks like facebook app can not know if I liked your fanpage or not? 

**To Reproduce**
1. Like fanpage
2. Click on 'Link Account'
3. See error

**Expected behavior**
This made me not be able to perform the next task.

**Screenshots**
![account linked](https://user-images.githubusercontent.com/6305130/43697071-890f553a-997c-11e8-91a5-2750689258e8.PNG)
![liked fanpage](https://user-images.githubusercontent.com/6305130/43697077-8ee36b0e-997c-11e8-8fd2-2273a3bf886d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 32bit
 - Browser Chrome
 - Version 67.0.3396.99 (Official Build) (32-bit)

**Comment by tiraxturumuz** [comment]
https://facebook.com/mohamad.nori.982

**Comment by ghost** [comment]
I have the same problem with Facebook and Twitter. Assignments fulfilled, but the PTS did not accrue.

**Comment by trottyosmy** [comment]
This my problem too. 
![workchain bug](https://user-images.githubusercontent.com/42069332/44299889-01c6d180-a2fe-11e8-9d54-b5d53223f96c.jpg)
![workchain bug 2](https://user-images.githubusercontent.com/42069332/44299898-4ce0e480-a2fe-11e8-9add-ae723a013d30.jpg)

**Comment by ipetrovic11** [comment]
Please allow system 2 hors to calculate PTS
