### ISSUE TITLE
Bounty page keep loading forever

### ISSUE THREAD

**Issue by tiennvdtn** [workchainio/bug-bounty#83]
**Describe the bug**
From workchain.io profile page, I click on 
**Our Bounty Program is Active! Head over to the Bounty Page to Learn More** button
Then Browser open bounty page, but It just show loading icon and could not go through.
When I check in console, saw this error:
`Failed to load https://api.workchain.io/bounty/get-data: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://workchain.io' is therefore not allowed access. The response had HTTP status code 500.`

**To Reproduce**
1. Go to workchain.io and login
2. Click on **Our Bounty Program is Active! Head over to the Bounty Page to Learn More**
3. See loader, page not display

**Expected behavior**
See bounty page

**Screenshots**
![image](https://user-images.githubusercontent.com/40050370/43698800-061d590c-9976-11e8-8d2a-a21d8c896cdc.png)

**Desktop:**
 - OS: [ Ubuntu]
 - Browser [chrome]
 - Version [67]

**Comment by ryanpaulfyfe** [comment]
This has been resolved, please let us know if you still experience this at; ping@workchain.io
