### ISSUE TITLE
Bounty Bug

### ISSUE THREAD

**Issue by Pitoys** [workchainio/bug-bounty#99]
Description:
Bug reported within campaign after 09:35 AM EST but on report it says it was submitted at 09:08 AM EST (before submission on Github timing)

To Reproduce

Go to workchain.io
Click on 'Bug Bounty'
Submit bug URL reported in GITHUB
Check timing of reported bug.
Expected behavior
Bug report timing should be the timing when it was reported.

Screenshots
workchain_period limit 6

Desktop (please complete the following information):
OS: Windows 10
Browser : chrome
Version : 67.0.3396.99

**Comment by Demilade2016** [comment]
Nice project

**Comment by xchep007** [comment]
Good

**Comment by ryanpaulfyfe** [comment]
Thanks for reporting our team will look into this.
